[package]
name = "tabby-db"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true

[features]
testutils = []
prod = []

[dependencies]
anyhow.workspace = true
chrono = { workspace = true, features = ["serde"] }
sqlx = { version = "0.7.3", features = ["sqlite", "chrono", "runtime-tokio"] }
tabby-common = { path = "../../crates/tabby-common" }
tokio = { workspace = true, features = ["fs"] }
uuid.workspace = true

[dev-dependencies]
assert_matches = "1.5.0"
tokio = { workspace = true, features = ["macros", "process"] }
