dist: bionic
language: cpp
compiler:
  - gcc
addons:
  apt:
    packages:
      - cmake
install:
  - make -j2 install
  - cd ..
before_script:
  - wget https://opennmt-models.s3.amazonaws.com/transliteration-aren-all.tar.gz
  - tar xf transliteration-aren-all.tar.gz -C tests/data/models/
script:
  - build/tests/ctranslate2_test tests/data

matrix:
  include:
    - name: "Intel MKL backend"
      env:
        - CT2_VERBOSE=1
        - CT2_USE_MKL=1
      sudo: true
      before_install:
        - wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB
        - sudo apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB
        - sudo sh -c 'echo deb https://apt.repos.intel.com/mkl all main > /etc/apt/sources.list.d/intel-mkl.list'
        - sudo apt-get update
        - sudo apt-get install -y intel-mkl-64bit-2020.3-111
        - mkdir build && cd build
        - cmake -DCMAKE_INSTALL_PREFIX=$PWD/../install -DWITH_TESTS=ON ..

    - name: "DNNL backend"
      env:
        - CT2_VERBOSE=1
      before_install:
        - wget https://github.com/oneapi-src/oneDNN/releases/download/v1.5/dnnl_lnx_1.5.0_cpu_gomp.tgz
        - tar xf dnnl*.tgz && rm dnnl*.tgz
        - mv dnnl* dnnl/
        - mkdir build && cd build
        - cmake -DCMAKE_INSTALL_PREFIX=$PWD/../install -DWITH_TESTS=ON -DWITH_MKL=OFF -DOPENMP_RUNTIME=COMP -DWITH_DNNL=ON -DCMAKE_PREFIX_PATH=$PWD/../dnnl ..

    - name: "Python package"
      language: python
      python:
        - "3.7"
      env:
        - TWINE_REPOSITORY_URL="https://upload.pypi.org/legacy/"
      services:
        - docker
      before_install:
        - docker run -v $PWD:/root -w /root quay.io/pypa/manylinux2010_x86_64 bash /root/python/tools/build_wheel.sh
        - pip install -r python/tests/requirements.txt
        - pip uninstall -y ctranslate2
        - pip install twine
      install:
        - pip install python/wheelhouse/*cp37*.whl
      script:
        - pytest python/tests/test.py
      after_success:
        - |
              if [[ -n $TRAVIS_TAG ]]; then
                  twine upload python/wheelhouse/*.whl
              fi
