[workspace]
members = [
    "crates/tabby",
    "crates/tabby-common",
    "crates/tabby-scheduler",
    "crates/tabby-download",
    "crates/tabby-inference",
    "crates/ctranslate2-bindings",
    "crates/rust-cxx-cmake-bridge",
    "crates/llama-cpp-bindings",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Meng Zhang"]
homepage = "https://github.com/TabbyML/tabby"

[workspace.dependencies]
lazy_static = "1.4.0"
serde = { version = "1.0", features = ["derive"] }
serdeconv = "0.4.1"
tokio = "1.28"
tokio-util = "0.7"
tracing = "0.1"
tracing-subscriber = "0.3"
anyhow = "1.0.71"
serde-jsonlines = "0.4.0"
tantivy = "0.19.2"
async-trait = "0.1.72"
reqwest = { version = "0.11.18" }
derive_builder = "0.12.0"
