[workspace]
resolver = "1"
members = [
    "crates/tabby",
    "crates/tabby-common",
    "crates/tabby-scheduler",
    "crates/tabby-download",
    "crates/tabby-inference",
    "crates/llama-cpp-bindings",
    "crates/http-api-bindings",
    "crates/aim-downloader",
    "crates/juniper-axum",
    "ee/tabby-webserver",
    "ee/tabby-db",
]

[workspace.package]
version = "0.8.0"
edition = "2021"
authors = ["Meng Zhang"]
homepage = "https://github.com/TabbyML/tabby"

[workspace.dependencies]
lazy_static = "1.4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
serdeconv = "0.4.1"
tokio = "1.28"
tracing = "0.1"
tracing-subscriber = "0.3"
anyhow = "1.0.71"
serde-jsonlines = "0.4.0"
tantivy = "0.21.0"
async-trait = "0.1.72"
reqwest = { version = "0.11.18" }
derive_builder = "0.12.0"
futures = "0.3.28"
async-stream = "0.3.5"
regex = "1.10.0"
thiserror = "1.0.49"
utoipa = "3.3"
axum = "0.6"
hyper = "0.14"
juniper = "0.15"
chrono = "0.4"
reqwest-eventsource = "0.5.0"

[workspace.dependencies.uuid]
version = "1.3.3"
features = [
    "v4",                # Lets you generate random UUIDs
    "fast-rng",          # Use a faster (but still sufficiently random) RNG
    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
]

[profile.dev.package]
insta.opt-level = 3
