schedule: "*/3 * * * *" # Run every 3rd minute

env:
  - PATH: "$PATH"
  - LOGS_DIR: "$LOGS_DIR"
  - DB_FILE: "$DB_FILE"
  - APP_DIR: /app
steps:
  - name: Collect Tabby
    dir: $APP_DIR
    command: ./tabby/tools/analytic/main.sh collect_tabby_server_logs
