[package]
name = "tabby-download"
version = "0.7.0-dev"
edition = "2021"

[dependencies]
tabby-common = { path = "../tabby-common" }
anyhow = { workspace = true }
tracing = { workspace = true }
tokio-retry = "0.3.0"
sha256 = "1.4.0"
aim = "1.8.5"
