[package]
name = "tabby-download"
version = "0.9.0-rc.2"
edition = "2021"

[dependencies]
aim-downloader = { path = "../aim-downloader" }
tabby-common = { path = "../tabby-common" }
anyhow = { workspace = true }
tracing = { workspace = true }
tokio-retry = "0.3.0"
sha256 = "1.4.0"
